### ISSUE TITLE
Missing v3.4 branch?

### ISSUE THREAD

**Issue by mmoayyed** [Evolveum/midpoint-overlay-example#2]
Based on this doc:
https://wiki.evolveum.com/display/midPoint/Customization+With+Overlay+Project

```
The example overlay project is located in the Evolveum/midpoint-overlay-example github repository:
Version
 
master
(development)	https://github.com/Evolveum/midpoint-overlay-example
3.4
(latest stable)	https://github.com/Evolveum/midpoint-overlay-example/tree/v3.4
```

There is no v3.4 branch here.

**Comment by semancik** [comment]
That's right. There is no v3.4 branch. But there is v3.4 tag. It looks to me that the URL is working.

**Comment by mmoayyed** [comment]
Thanks. Would it be more suitable if you turn that into a branch as well? I presume that if changes are made, it would be easy to pull them down rather than re-downloading a new tag manually.

**Comment by semancik** [comment]
v3.4 tag marks the release 3.4 of the midpoint-overlay-example project. It matches the 3.4 release of midPoint, but as midpoint-overlay-example is a separate project it has its own tag to mark its own release.
In case that there will be some changes I will do them on master branch. It is the easiest approach to avoid unnecessary branches. Yes, those changes will probably use midPoint 3.5-SNAPSHOT instead of 3.4. But that's still OK. To keep our overhead down we only support the most recent midPoint version for the community and we are not automatically backporting any fixes to older versions. Support for older versions means additional overhead and that overhead needs to be paid for in form of commercial support (subscription). If such a backport is needed I will create a new "support" branch for that. But as this is a very small example project I think that this won't be necessary. It is possible that new midPoint version will be released before anyone needs any fix into this tiny project.

**Comment by mmoayyed** [comment]
Thanks for the summary, cool. Help me understand a given deployment workflow better please:

1. I have used this overlay to do my midPoint deployment. Let's say I am running a brand new just-released 3.4.
2. 4 months into my deployment, I realize I have run into a bug.
3. I also then learn that the fix is applied to 3.5, and will no longer [possibly] be backported to 3.4 
4. So to continue, I may have to upgrade to 3.5-SNAPSHOT (unless I am willing to pay for support and have the change be backported)
5. Given I am 3 months into deployment now, I also realize switching to 3.5 may break a few other things in my configuration. Minor release, and all. Things change, etc.
6. So at this point, my options would be to either sign up for commercial support or sort of figure out how to get my 3.5-SNAPSHOT deployment in place.

**Comment by semancik** [comment]
Yes. That's pretty much it. Or you can create a fork of the 3.4 support branch and backport the fix yourself. The source code part of the backport is usually easy (just git cherry-pick). The hard part is the testing that it works and that it does not break anything else.

But generally speaking it is usually OK to upgrade to the newest snapshot. The risk is usually quite acceptable. We are trying quite hard to keep snapshots in a good working condition. See https://bamboo.evolveum.com/browse/MID-TRUNK

**Comment by mmoayyed** [comment]
Got it. Thanks very much for your patience with me.
